### ISSUE TITLE
Reply to long messages

### ISSUE THREAD

**Issue by metbril** [darkcl/mastodon-ios-issue#3]
When you reply to a long message you can't see your own text because the original text is in the way. There is too little space left for the text box.

**Comment by darkcl** [comment]
Will be showing 2 lines of original text, version now waiting apple approval

**Comment by imlps** [comment]
I was about to report the same thing, thanks! :)

**Comment by darkcl** [comment]
Version 1.1 is released :) Reply message will constraint to two lines like this
![img_2219](https://cloud.githubusercontent.com/assets/446404/25563256/8cf359a4-2dca-11e7-8bef-36e0c44b7421.PNG)
