### ISSUE TITLE
Typo: Notification instead of Notificaiton :)

### ISSUE THREAD

**Issue by imlps** [darkcl/mastodon-ios-issue#5]
Hi there,

Thanks for developing the app, it looks really promising! :)

As mentioned in the title, there's a spelling error in the tab bar which says "Notificaiton".

**Comment by imlps** [comment]
As well as "Fedrated", it should be "Federated". :)

**Comment by darkcl** [comment]
Will be fix in 1.2

**Comment by darkcl** [comment]
Bug Fixed in version 1.2
