### ISSUE TITLE
Can't get instance to show up in instance list

### ISSUE THREAD

**Issue by phoneboy** [darkcl/mastodon-ios-issue#9]
I had previously logged into noagendasocial.com in the app (version 1.3), then deleted the app.
I then redownloaded and reinstalled the app.
When I enter noagendasocial.com as the instance to log into, I am not prompted to log in and it appears to be reusing my previous authentication token.
More importantly, I do not see noagendasocial.com as an option in the Instance list.
I can still switch to this instance by manually entering noagendasocial.com, but it is never added to the Instance list.

Can you fix this in an upcoming release?

**Comment by darkcl** [comment]
Bug Fixed in version 1.4
